name: Notify Slack

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    name: Send Slack Notification
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify Slack
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            EMOJI="🎉"
            STATUS="PASSED"
          else
            EMOJI="💥"
            STATUS="FAILED"
          fi
          
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"${EMOJI} ${{ github.repository }} | ${{ github.ref_name }} | ${STATUS}\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Details>\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}