name: Scan Docker Image with Trivy

on:
  workflow_call:

jobs:
  scan:
    name: Scan Docker Image with Trivy
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ env.DOCKER_IMAGE_NAME }}-${{ github.sha }}
          path: ./

      - name: Load Docker image from tar file
        run: |
          echo "=== Chargement de l'image Docker depuis le fichier tar ==="
          docker load -i docker-image.tar
          echo "== Images chargées =="
          docker images
      - name: Set Date
        id: set-date
        run: echo "DATE=$(date +%m.%d.%Y)" >> $GITHUB_ENV

      - name: Create output directory
        run: mkdir -p "GitHub Actions/Trivy Automation"

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.57.0
      - name: Download Trivy vulnerability database
        run: trivy image --download-db-only

      - name: Run Trivy vulnerability scanner
        run: |
          OUTPUT_FILE="GitHub Actions/Trivy Automation/scan-results-${DATE}.json"
          mkdir -p "GitHub Actions/Trivy Automation"
          trivy image --format json --ignore-unfixed --skip-files --vuln-type os,library --severity CRITICAL,HIGH,MEDIUM,LOW -o "$OUTPUT_FILE" ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Upload scan results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results-${{ env.DATE }}
          path: GitHub Actions/Trivy Automation/
          retention-days: 7
