name: Secrets Detection

on:
  workflow_call:

jobs:
  gitleaks:
    name: Secret Detection with GitLeaks
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create directories
        run: |
          mkdir -p "GitHub Actions/GitLeaks/Reports"

      - name: Run GitLeaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload GitLeaks reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-reports-${{ github.sha }}
          path: |
            leaks.json
            leaks.sarif
          retention-days: 7
