name: Secrets Detection

on:
  workflow_call:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: wget -qO- https://github.com/gitleaks/gitleaks/releases/download/v8.18.1/gitleaks_8.18.1_linux_x64.tar.gz | tar xz && ./gitleaks detect --source . --report-format json --report-path report.json || true

      - uses: actions/upload-artifact@v4
        with:
          name: secrets-report
          path: report.json
